# Setup
title:        Eclipse Lyo
tagline:      Technology Blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Yash Khatri
  url:        http://yashkhatri.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
