# Setup
title:        Pumori
tagline:      Technology Blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Neeraj Bhusare
  url:        http://nbhusare.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
