# Setup
title:        Working with Eclipse Lyo and Linked Data
tagline:      Technology Blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Yash Khatri
  url:        http://www.yashkhatri.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
